// src/App.tsx
import { useAppStore } from './store/useAppStore'
import { Header } from './components/layout/Header'
import { Sidebar } from './components/layout/Sidebar'
import { PropertyPanel } from './components/layout/PropertyPanel'
import { MapContainer } from './components/map/MapContainer'

export default function App() {
  const sidebarOpen = useAppStore((s) => s.sidebarOpen)
  const propertyPanelOpen = useAppStore((s) => s.propertyPanelOpen)

  return (
    <div className="h-screen w-screen flex flex-col overflow-hidden bg-gray-900 text-white">
      <Header />
      <div className="flex flex-1 overflow-hidden">
        {sidebarOpen && <Sidebar />}
        <main className="flex-1 relative">
          <MapContainer />
        </main>
        {propertyPanelOpen && <PropertyPanel />}
      </div>
    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import { useAppStore } from './stores/appStore'
import AppHeader from './components/layout/AppHeader.vue'
import AppSidebar from './components/layout/AppSidebar.vue'
import PropertyPanel from './components/layout/PropertyPanel.vue'
import MapContainer from './components/map/MapContainer.vue'

const store = useAppStore()
</script>

<template>
  <div class="h-screen w-screen flex flex-col overflow-hidden bg-gray-900 text-white">
    <AppHeader />
    <div class="flex flex-1 overflow-hidden">
      <AppSidebar v-if="store.sidebarOpen" />
      <main class="flex-1 relative">
        <MapContainer />
      </main>
      <PropertyPanel v-if="store.propertyPanelOpen" />
    </div>
  </div>
</template>
